import type { QualityReferentialConfig } from "@crc/types";

/** Référentiel par défaut (feuille Excel 1_Referentiel). */
export const DEFAULT_QUALITY_REFERENTIAL: QualityReferentialConfig = {
  thresholds: {
    plafondMinusOne: 8,
    plafondBlocking: 12,
    conformeMin: 14,
    coachingMax: 14,
    mentionExcellent: 18,
    mentionTresSatisfaisant: 16,
    mentionSatisfaisant: 14,
    mentionAmeliorer: 12,
  },
  criteria: [
    {
      id: "accueil_salutation",
      domain: "Accueil",
      name: "Salutation professionnelle",
      maxPoints: 2,
      blocking: true,
      allowThree: false,
      expected:
        "Accueil clair : identification du cabinet + praticien, annonce du service, formule de politesse.",
      rubrics: {
        "-1": "Non-conformité majeure (ex : propos inadaptés / agressifs / discrimination).",
        "0": "Aucun élément attendu : pas d'identification, pas de salutation, entrée brusque.",
        "1": "Partiel : salutation présente mais information incomplète (cabinet/praticien manquant).",
        "2": "Conforme : salutation + identification complète, ton professionnel dès le début.",
      },
    },
    {
      id: "accueil_ton",
      domain: "Accueil",
      name: "Ton & courtoisie (empathie)",
      maxPoints: 2,
      blocking: false,
      allowThree: false,
      expected: "Vouvoyer, ton calme et bienveillant, respect du patient et des contraintes.",
      rubrics: {
        "-1": "Non-conformité majeure (impolitesse, jugement, sarcasme, interruption agressive).",
        "0": "Ton inadapté : tutoiement, impatience, absence de courtoisie.",
        "1": "Variable : courtoisie partielle, empathie insuffisante, interruptions.",
        "2": "Conforme : courtois, empathique, maîtrise des échanges, posture de service.",
      },
    },
    {
      id: "identite_rgpd",
      domain: "Identification",
      name: "Vérification identité patient (RGPD)",
      maxPoints: 2,
      blocking: true,
      allowThree: false,
      expected:
        "Vérifier identité avant toute info : NOM + prénom + date de naissance (ou autre procédure client).",
      rubrics: {
        "-1": "Non-conformité majeure : divulgation d'informations sans vérification / erreur d'identité.",
        "0": "Aucune vérification ou vérification non conforme à la procédure client.",
        "1": "Vérification partielle : 1 élément seulement ou contrôle tardif.",
        "2": "Conforme : vérification complète et au bon moment, respect confidentialité.",
      },
    },
    {
      id: "rdv_exactitude",
      domain: "Gestion RDV",
      name: "Exactitude des informations (RDV/consignes)",
      maxPoints: 3,
      blocking: true,
      allowThree: true,
      expected:
        "Informations exactes : motif, praticien, date/heure, lieu, consignes, vérification disponibilité.",
      rubrics: {
        "-1": "Non-conformité majeure : RDV pris sur mauvais praticien / date, consigne critique erronée.",
        "0": "Informations erronées ou manquantes : risque patient / insatisfaction.",
        "1": "Partiel : informations correctes mais incomplètes (une info clé manque).",
        "2": "Conforme : informations complètes, contrôle cohérence, reformule pour valider.",
        "3": "Premium : conforme + anticipe (propose alternatives, rappelle pièces/consignes).",
      },
    },
    {
      id: "rdv_procedure",
      domain: "Gestion RDV",
      name: "Respect procédure client (outil / règles)",
      maxPoints: 3,
      blocking: true,
      allowThree: true,
      expected:
        "Application stricte des consignes (priorités, urgences, transferts, messages, délais).",
      rubrics: {
        "-1": "Non-conformité majeure : non-respect d'une règle critique (urgence, confidentialité, circuit).",
        "0": "Procédure non respectée : consignes ignorées / utilisation outil incorrecte.",
        "1": "Partiel : une partie des consignes appliquée, oubli(s) notable(s).",
        "2": "Conforme : consignes appliquées, traçabilité correcte, utilisation outil maîtrisée.",
        "3": "Premium : conforme + sécurise (checklist, double-contrôle, mention claire des exceptions).",
      },
    },
    {
      id: "communication_clarte",
      domain: "Communication",
      name: "Clarté de l'expression (orale/écrite)",
      maxPoints: 2,
      blocking: false,
      allowThree: false,
      expected:
        "Message structuré : phrases courtes, vocabulaire simple, articulation, écrit sans ambiguïté.",
      rubrics: {
        "-1": "Non-conformité majeure : propos incompréhensibles / information trompeuse volontaire.",
        "0": "Incompréhensible : message confus, erreurs empêchant la compréhension.",
        "1": "Partiel : compréhensible mais manque de structure ou imprécisions.",
        "2": "Conforme : clair, structuré, reformulation si nécessaire.",
      },
    },
    {
      id: "communication_ecoute",
      domain: "Communication",
      name: "Écoute active & reformulation",
      maxPoints: 2,
      blocking: false,
      allowThree: false,
      expected: "Laisse s'exprimer, questionne, reformule, confirme le besoin avant d'agir.",
      rubrics: {
        "-1": "Non-conformité majeure : coupe systématiquement, ignore le besoin, escalade inutile.",
        "0": "Aucune écoute : pas de question, pas de reformulation, prend des décisions sans vérifier.",
        "1": "Partiel : questions présentes mais reformulation/validation insuffisante.",
        "2": "Conforme : écoute active, reformule et valide, adapte sa réponse.",
      },
    },
    {
      id: "conclusion_synthese",
      domain: "Conclusion",
      name: "Synthèse & confirmation (récap)",
      maxPoints: 2,
      blocking: false,
      allowThree: false,
      expected: "Récapitule : RDV/infos clés, consignes, prochaines étapes, vérifie l'accord.",
      rubrics: {
        "-1": "Non-conformité majeure : conclut sur une information critique fausse / non validée.",
        "0": "Aucune synthèse : fin sans récapitulatif, informations clés non confirmées.",
        "1": "Partiel : récap incomplet, validation incomplète.",
        "2": "Conforme : récap complet + confirmation explicite.",
      },
    },
    {
      id: "conclusion_cloture",
      domain: "Conclusion",
      name: "Clôture professionnelle",
      maxPoints: 2,
      blocking: false,
      allowThree: false,
      expected: "Remercie, formule de clôture, disponibilité, prise de congé propre.",
      rubrics: {
        "-1": "Non-conformité majeure : clôture brusque/impolie, abandon de l'appel.",
        "0": "Clôture absente ou inadaptée.",
        "1": "Partiel : clôture présente mais peu professionnelle ou expéditive.",
        "2": "Conforme : clôture nette, polie, orientée service.",
      },
    },
  ],
};
